### ISSUE TITLE
integration-tests.cpp won't compile on Ubuntu (auto_ptr is deprecated)

### ISSUE THREAD

**Issue by nolanhergert** [m-mcgowan/spark-flashee-eeprom#12]
FIX (for compiling): Searching [around the nets](http://stackoverflow.com/questions/2404115/is-auto-ptr-deprecated) indicates std::unique_ptr is now in favor instead of auto_ptr. It works after that.

There are two files this affects: `test/FlashDeviceTest.h` and `examples/integration-test.cpp`

**Comment by m-mcgowan** [comment]
Thanks for this - if you have it working - could you submit a PR with the change to std::unique_ptr?

**Comment by nolanhergert** [comment]
Yep! https://github.com/m-mcgowan/spark-flashee-eeprom/pull/17

Hopefully I will have more significant ones in the future :)

**Comment by m-mcgowan** [comment]
Thanks! PR merged.
