### ISSUE TITLE
List of supported chips

### ISSUE THREAD

**Issue by jefflab** [m-mcgowan/spark-flashee-eeprom#19]
It would be great if there was documentation which flash SPI chips are supported. For example, winbond has a [chip with the same footprint]( http://www.winbond.com/resource-files/w25q128fv_revhh1_100913_website1.pdf). It would be great to know if it would work, or if I should stick with the chip on the core.

**Comment by m-mcgowan** [comment]
If a flash device isn't supported, you just have to write a low-level driver for it and plug it in. But this library is presently geared towards Particle devices, but it wouldn't be difficult to target other devices too.

**Comment by jefflab** [comment]
Makes sense. Hopefully we can contribute a winbond driver in the future. thanks!
