### ISSUE TITLE
Flash write duration

### ISSUE THREAD

**Issue by aaraujo11** [m-mcgowan/spark-flashee-eeprom#20]
Hi @m-mcgowan ,

I'm experiencing some unstable timings while writing to the flash circular buffer. A writing usually lasts 732us, however from time to time it takes 15390us. Any clue on what the problem may be?

To emulate my issue, i had tested with this simple code below and the result is the same.

Thanks in advance!

```
void loop() {

       buff_test = Flashee::Devices::createCircularBuffer(4096*1, 4096*384);

        while(1){
            delay(512);
            byte tab[76];
            for(int i=0; i<76;i++){
                tab[i]=(byte)i;
            }
            int cnt=micros();
            buff_test->write(tab, 76);
            int cntF=micros()-cnt;
            Serial.print(cntF);
        }
}
```

**Comment by aaraujo11** [comment]
After some debug, the main reason for this time consumption (15390us), it occurs in write_impl() function when the offset reaches zero and  run the flash.erasePage(). The erasePage routine is the reason for those timings. Is possible to decrease the time of the erasepage?

**Comment by m-mcgowan** [comment]
Not to my knowledge - that's how long the hardware takes to erase the page.

**Comment by aaraujo11** [comment]
Hi @m-mcgowan, i deal with it by fed the memory buffer, when my routine had a free open time window, instead do it during my "real time" routine. Thanks
