### ISSUE TITLE
Is external NAND flash supported?

### ISSUE THREAD

**Issue by rahulgopinathan** [m-mcgowan/spark-flashee-eeprom#28]

**Comment by m-mcgowan** [comment]
Some more details would be helpful!   The external flash on P1 is supported. If you have another flash module in mind then it probably is not supported out of the box, but it is relatively straightforward to implement your own driver class for the specific flash module you are using.

**Comment by m-mcgowan** [comment]
Given the age of this, I'm going to close it. Feel free to reopen to discuss the topic further.
